#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 16 01:05:43 2022

@author: noah01px2019
"""
from matplotlib import pyplot as plt
import random
import numpy as np
import matplotlib.animation as animation

dots = 2000
dotsperframe = 5
Count = 0

circx = np.linspace(0,1,100)
circy = np.sqrt(1-circx**2)

x = []
y = []

xo = []
yo = []

for i in range(1,dots):
    
    newx = random.random()
    newy = random.random()   

    

	# Mention x and y limits to define their range
    plt.xlim(0, 1)
    plt.ylim(0, 1)
    
    plt.gca().set_aspect('equal', adjustable='box')
    plt.xlabel("x")
    plt.ylabel("y")
    
    
    if (newx**2 + newy**2 < 1):
        Count += 1
        x.append(newx)
        y.append(newy)
    else:
        xo.append(newx)
        yo.append(newy)
        
    if i % dotsperframe == 0:
        plt.title("pi = " + str("{:.4f}".format(round(4*Count/i,4))))
        plt.plot(circx,circy)
        plt.scatter(x, y, color = 'red',marker = ".")
        plt.scatter(xo, yo, color = 'green',marker = ".")
        plt.show()


pi = 4*Count/i
print(pi)